modified readme

diff --git a/.github/workflows/deploy-infra.yml b/.github/workflows/deploy-infra.yml
--- a/.github/workflows/deploy-infra.yml
+++ b/.github/workflows/deploy-infra.yml
@@ -1,56 +1,59 @@
-name: Terraform Plan & Apply
+# name: Terraform Plan & Apply
 
-on:
-  push:
-    branches: [main]
-    paths:
-      - "./infra"
+# on:
+#   push:
+#     branches:
+#       - main
 
-env:
-  AWS_REGION: eu-west-2
+# env:
+#   AWS_REGION: eu-west-2
 
-jobs:
-  terraform:
-    runs-on: ubuntu-latest
+# jobs:
+#   terraform:
+#     runs-on: ubuntu-latest
+#     permissions:
+#       id-token: write
+#       contents: read
 
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@v4
+#     defaults:
+#       run:
+#         working-directory: ./infra
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
-          aws-region: eu-west-2
+#     steps:
+#       - name: Checkout repo
+#         uses: actions/checkout@v4
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3.1.2
-        with:
-          terraform_version: 1.11.1
+#       - name: Configure AWS credentials
+#         uses: aws-actions/configure-aws-credentials@v4
+#         with:
+#           role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
+#           aws-region: eu-west-2
 
-      - name: Terraform Init
-        working-directory: "./infra"
-        run: terraform init
+#       - name: Setup Terraform
+#         uses: hashicorp/setup-terraform@v3.1.2
+#         with:
+#           terraform_version: 1.11.1
 
-      - name: Checkov
-        uses: bridgecrewio/checkov-action@master
-        with:
-          framework: terraform
-          soft_fail: true
-          output_format: cli,sarif
-          output_file_path: checkov-results-terraform.sarif
+#       - name: Checkov
+#         uses: bridgecrewio/checkov-action@master
+#         with:
+#           framework: terraform 
+#           soft_fail: true
+#           output_format: cli,sarif
+#           output_file_path: checkov-results-terraform.sarif
 
-      - name: Upload Checkov scan results to GitHub Security tab
-        uses: github/codeql-action/upload-sarif@v3
-        if: success() || failure()
-        with:
-          sarif_file: 'checkov-results-terraform.sarif'
-          wait-for-processing: true
+#       - name: Upload Checkov scan results to GitHub Security tab
+#         uses: github/codeql-action/upload-sarif@v3
+#         if: success() || failure()
+#         with:
+#           sarif_file: checkov-results-terraform.sarif
+#           wait-for-processing: true
 
-      - name: Terraform Plan
-        working-directory: "./infra"
-        run: terraform plan -out=tfplan -var="environment=dev" -var="aws_region=eu-west-2"
+#       - name: Terraform Init
+#         run: terraform init
 
-      - name: Terraform Apply
-        working-directory: "./infra"
-        run: terraform apply -auto-approve tfplan
+#       - name: Terraform Plan
+#         run: terraform plan -out=tfplan
+
+#       - name: Terraform Apply
+#         run: terraform apply -auto-approve tfplan
